export const AMBU_LIST_REQUEST = 'AMBU_LIST_REQUEST'
export const AMBU_LIST_SUCCESS = 'AMBU_LIST_SUCCESS'
export const AMBU_LIST_FAIL = 'AMBU_LIST_FAIL'

export const AMBU_DETAILS_REQUEST = 'AMBU_DETAILS_REQUEST'
export const AMBU_DETAILS_SUCCESS = 'AMBU_DETAILS_SUCCESS'
export const AMBU_DETAILS_FAIL = 'AMBU_DETAILS_FAIL'
