export const APPOINMENT_CREATE_REQUEST = 'APPOINMENT_CREATE_REQUEST'
export const APPOINMENT_CREATE_SUCCESS = 'APPOINMENT_CREATE_SUCCESS'
export const APPOINMENT_CREATE_FAIL = 'APPOINMENT_CREATE_FAIL'