export const MED_LIST_REQUEST = "MED_LIST_REQUEST";
export const MED_LIST_SUCCESS = "MED_LIST_SUCCESS";
export const MED_LIST_FAIL = "MED_LIST_FAIL";

export const MED_DETAILS_REQUEST = "MED_DETAILS_REQUEST";
export const MED_DETAILS_SUCCESS = "MED_DETAILS_SUCCESS";
export const MED_DETAILS_FAIL = "MED_DETAILS_FAIL";

export const MED_DELETE_REQUEST = "MED_DELETE_REQUEST";
export const MED_DELETE_SUCCESS = "MED_DELETE_SUCCESS";
export const MED_DELETE_FAIL = "MED_DELETE_FAIL";

export const MED_CREATE_REQUEST = "MED_CREATE_REQUEST";
export const MED_CREATE_SUCCESS = "MED_CREATE_SUCCESS";
export const MED_CREATE_FAIL = "MED_CREATE_FAIL";
export const MED_CREATE_RESET = "MED_CREATE_RESET";

export const MED_UPDATE_REQUEST = "MED_UPDATE_REQUEST";
export const MED_UPDATE_SUCCESS = "MED_UPDATE_SUCCESS";
export const MED_UPDATE_FAIL = "MED_UPDATE_FAIL";
export const MED_UPDATE_RESET = "MED_UPDATE_RESET";
